/* Chapitre 2 — Méthodes physiques d'analyse — CARTES MÉMO
   Une carte = { q: "question (recto)", r: "réponse (verso)" }. Markdown accepté ; formules entre $…$. */
definirContenu("chimie/02-methodes-physiques-analyse", "cartes", [
  /* pH */
  { q: "Définition du pH ?", r: "$$\\mathrm{pH} = -\\log\\left(\\frac{[\\mathrm{H_3O^+}]}{c^0}\\right)$$\n\n[H₃O⁺] en mol·L⁻¹, pH sans unité, c⁰ = 1 mol·L⁻¹." },
  { q: "Comment calculer [H₃O⁺] à partir du pH ?", r: "$$[\\mathrm{H_3O^+}] = c^0 \\times 10^{-\\mathrm{pH}}$$\n\nTouche **10ˣ** de la calculatrice." },
  { q: "Que vaut c⁰ et à quoi sert-il ?", r: "c⁰ = **1 mol·L⁻¹ exactement** (concentration standard). Il rend le quotient [H₃O⁺]/c⁰ **sans unité** ; son nombre de chiffres significatifs ne change pas le résultat." },
  { q: "Dans quel domaine les relations du pH sont-elles valables ?", r: "Pour des concentrations en H₃O⁺ **ou** en HO⁻ **inférieures à 1,0 × 10⁻¹ mol·L⁻¹**." },
  { q: "pH d'un jus de citron = 2,50. [H₃O⁺] ?", r: "[H₃O⁺] = 10⁻²·⁵⁰ = **3,2 × 10⁻³ mol·L⁻¹**" },
  { q: "Sans calculatrice : pH si [H₃O⁺] = 1,0 × 10⁻⁵ mol·L⁻¹ ? Et [H₃O⁺] si pH = 3,00 ?", r: "pH = **5,00**\n\n[H₃O⁺] = **1,0 × 10⁻³ mol·L⁻¹**" },
  { q: "[H₃O⁺] = 2,0 × 10⁻³ mol·L⁻¹ et log 2 = 0,30. pH ?", r: "pH = −log(2,0) − log(10⁻³) = −0,30 + 3,00 = **2,70**" },
  { q: "Propriétés du logarithme décimal à connaître ?", r: "log(ab) = log a + log b\n\nlog(a/b) = log a − log b\n\nlog(10ˣ) = x (réciproque : puissance de dix)" },
  { q: "Si on divise [H₃O⁺] par 10, que devient le pH ? Par 100 ?", r: "Le pH **augmente de 1** (÷ 10) ; de **2** (÷ 100). Ex. : pH 2,00 → 3,00 → 4,00." },
  { q: "pH faible : [H₃O⁺] grande ou petite ?", r: "**Grande.** Plus la solution est concentrée en H₃O⁺ (acide), plus le pH est petit." },
  { q: "Quelles touches de la calculatrice pour le pH ?", r: "**log** et **10ˣ** — à ne pas confondre avec la notation scientifique (×10ˣ / EE) ni avec « × 1 0 ^ »." },
  { q: "Trois façons de mesurer le pH et leur précision ?", r: "**pH-mètre** avec sonde (au **centième**, le plus précis, sonde fragile) ; **papier pH** (à l'unité) ; **indicateur coloré** comme le BBT (à l'unité)." },
  /* Spectroscopie */
  { q: "Qu'est-ce qu'un spectre UV-visible ?", r: "Graphique de l'**absorbance A** (sans unité) en fonction de la **longueur d'onde λ** (en nm)." },
  { q: "De quoi dépend l'allure d'un spectre UV-visible ?", r: "De la **concentration** de l'espèce absorbante, de la **nature du solvant** et de l'**espèce chimique** étudiée → peut servir à identifier une espèce." },
  { q: "Domaine des longueurs d'onde visibles ? Quand une solution est-elle incolore ?", r: "**400 nm à 800 nm.** Une solution est incolore si elle n'absorbe pas dans le visible (ex. acide salicylique : maxima à 236 et 310 nm, dans l'UV)." },
  { q: "Qu'est-ce qu'un spectre infrarouge ?", r: "Graphique de la **transmittance T** (en %) en fonction du **nombre d'onde σ** = 1/λ (en cm⁻¹)." },
  { q: "Que signifie T = 100 % sur un spectre IR ?", r: "L'espèce **n'absorbe pas** à cette longueur d'onde. T < 100 % ⇔ absorption (bande = creux)." },
  { q: "À quoi sert un spectre IR ? Quelles sont les 3 étapes pour identifier une molécule ?", r: "Identifier une espèce ou un **groupe caractéristique** (les bandes sont caractéristiques de liaisons).\n\n1. Repérer les liaisons (nombres d'onde) ; 2. identifier les groupes ; 3. les chercher dans la formule." },
  { q: "Bande IR de la liaison O–H (alcool, acide) ?", r: "**3 200 à 3 600 cm⁻¹**, bande **large**." },
  { q: "Bande IR de la liaison C=O ?", r: "**Vers 1 700 cm⁻¹**, bande **fine et profonde** (aldéhyde, cétone, acide carboxylique, ester, amide)." },
  { q: "Bande IR de la liaison N–H (amine, amide) ?", r: "**3 100 à 3 500 cm⁻¹**, parfois **deux bandes**." },
  { q: "Bandes IR : C–H ? C–O (ester) ?", r: "C–H : vers **2 800 – 3 000 cm⁻¹** (aldéhyde : 2 800).\n\nC–O : **1 300 cm⁻¹**." },
  { q: "Spectre IR d'une molécule C₄H₈O avec bandes à 2 961 et 1 718 cm⁻¹, sans bande large vers 3 300 : butanone (cétone) ou but-3-én-2-ol (alcool) ?", r: "**Butanone** : C–H (2 961) et **C=O** (1 718, fine et profonde), pas de O–H." },
  /* Conductance / conductivité */
  { q: "Qu'est-ce qu'une solution électrolytique ?", r: "Une solution qui contient des **ions** (elle conduit le courant)." },
  { q: "Définition et unité de la conductance G ?", r: "$$G = \\frac{i}{u} = \\frac{1}{R}$$\n\nG en **siemens (S)**, i en A, u en V." },
  { q: "u = 0,50 V et i = 124 μA. Conductance ?", r: "G = 124 × 10⁻⁶ / 0,50 = **2,5 × 10⁻⁴ S**" },
  { q: "De quoi dépend la conductance G d'une cellule ?", r: "De l'**aire S** des électrodes immergées, de la **distance ℓ** entre elles, de la **température**, de la **concentration et de la nature** des ions." },
  { q: "Réglages du montage pour mesurer une conductance ?", r: "GBF **sinusoïdal 1 kHz** ; voltmètre et ampèremètre en mode **AC**." },
  { q: "Définition et unités de la conductivité σ ?", r: "$$\\sigma = G\\,\\frac{\\ell}{S}$$\n\nσ en **S·m⁻¹**, G en S, ℓ en **m**, S en **m²**." },
  { q: "Différence entre conductance et conductivité ?", r: "**G** dépend de la cellule (S, ℓ) et de la solution.\n\n**σ** ne dépend que de la **solution** (température, nature et concentration des ions)." },
  { q: "Qu'appelle-t-on constante de cellule ?", r: "Le quotient **ℓ/S** (en m⁻¹ ou cm⁻¹) — parfois **S/ℓ** (en m ou cm). Regarder l'unité." },
  { q: "S = 1,0 cm², ℓ = 2,0 cm, G = 1,2 × 10⁻³ S. Conductivité ?", r: "Convertir : S = 1,0 × 10⁻⁴ m², ℓ = 2,0 × 10⁻² m.\n\nσ = 1,2 × 10⁻³ × 2,0 × 10⁻² / 1,0 × 10⁻⁴ = **0,24 S·m⁻¹**" },
  { q: "Qu'est-ce que la conductivité molaire ionique λ ? Unité ?", r: "Grandeur qui caractérise l'influence de la **nature** d'un ion sur la conductivité ; en **S·m²·mol⁻¹** (parfois mS·m²·mol⁻¹) ; dépend de la température." },
  { q: "Loi de Kohlrausch ?", r: "$$\\sigma = \\sum_i \\lambda_{\\mathrm{X}_i}[\\mathrm{X}_i]$$\n\nσ en S·m⁻¹, λ en S·m²·mol⁻¹, **[Xᵢ] en mol·m⁻³**." },
  { q: "Domaine de validité de la loi de Kohlrausch ?", r: "Concentrations **inférieures à 1,0 × 10⁻² mol·L⁻¹** (10 mol·m⁻³)." },
  { q: "Convertir 1 mol·L⁻¹ en mol·m⁻³. Et 1 mol·m⁻³ en mol·L⁻¹ ?", r: "1 mol·L⁻¹ = **10³ mol·m⁻³** (car 1 L = 10⁻³ m³).\n\n1 mol·m⁻³ = **10⁻³ mol·L⁻¹**." },
  { q: "Quels ions ont les plus grandes conductivités molaires ioniques ?", r: "**H₃O⁺** (35,0 × 10⁻³ S·m²·mol⁻¹) puis **HO⁻** (19,8 × 10⁻³). Les autres : de 5 à 16 × 10⁻³." },
  { q: "Solution : [H₃O⁺] = 2,00 × 10⁻², [NO₃⁻] = 1,00 × 10⁻², [SO₄²⁻] = 5,00 × 10⁻³ mol·L⁻¹. Conductivité ?", r: "Convertir en mol·m⁻³ : 20,0 ; 10,0 ; 5,00.\n\nσ = 35,0×10⁻³×20,0 + 7,1×10⁻³×10,0 + 16,0×10⁻³×5,00 = **0,851 S·m⁻¹**" },
  { q: "Nitrate de nickel Ni(NO₃)₂ de concentration c : équation de dissolution et concentrations des ions ?", r: "Ni(NO₃)₂(s) → Ni²⁺(aq) + 2 NO₃⁻(aq)\n\n[Ni²⁺] = **c** et [NO₃⁻] = **2c**" },
  { q: "Nitrate de nickel : exprimer c en fonction de σ.", r: "σ = λ<sub>Ni²⁺</sub>·c + λ<sub>NO₃⁻</sub>·2c = (λ<sub>Ni²⁺</sub> + 2 λ<sub>NO₃⁻</sub>)·c\n\ndonc $c = \\dfrac{\\sigma}{\\lambda_{\\mathrm{Ni^{2+}}} + 2\\lambda_{\\mathrm{NO_3^-}}}$ (en mol·m⁻³)" },
  { q: "σ = 5,00 × 10⁻² S·m⁻¹ pour Ni(NO₃)₂ ; λ(Ni²⁺) = 10,8 × 10⁻³, λ(NO₃⁻) = 7,1 × 10⁻³ S·m²·mol⁻¹. c ?", r: "c = 5,00 × 10⁻² / (10,8 × 10⁻³ + 2 × 7,1 × 10⁻³) = **2,00 mol·m⁻³ = 2,00 × 10⁻³ mol·L⁻¹**" },
  /* Dosage par étalonnage */
  { q: "Qu'est-ce qu'un dosage par étalonnage ?", r: "Détermination de la concentration d'une solution à l'aide d'une **courbe d'étalonnage** tracée avec des **solutions étalons** de concentrations connues." },
  { q: "Les 6 étapes d'un dosage par étalonnage ?", r: "1. Préparer une échelle de **solutions étalons** (dilutions). 2. Mesurer la grandeur (A, G, σ) pour chacune. 3. Tracer le **graphique** (grandeur en ordonnée, c en abscisse). 4. Tracer la **courbe-modèle**. 5. Mesurer la grandeur pour l'inconnue. 6. Lire **graphiquement** sa concentration." },
  { q: "Qu'est-ce qu'une solution étalon ? une échelle de teintes ?", r: "Solution de **concentration connue** obtenue par dilution. Si les étalons sont colorés, ils forment une **échelle de teintes** : on peut utiliser l'absorbance." },
  { q: "Condition pour un dosage par étalonnage conductimétrique ?", r: "La solution doit contenir **un seul soluté apporté** (un seul solide ionique dissous)." },
  { q: "Dosage conductimétrique du KCl : G = 2,8 mS et la droite d'étalonnage donne 4,7 mmol·L⁻¹. Concentration en mol·L⁻¹ ?", r: "c = **4,7 × 10⁻³ mol·L⁻¹**" },
  { q: "Loi de Beer-Lambert ?", r: "$$A_\\lambda = \\varepsilon\\,\\ell\\,c$$\n\nA sans unité, ℓ en **cm**, c en **mol·L⁻¹**, ε en **L·mol⁻¹·cm⁻¹** (coefficient d'absorption molaire)." },
  { q: "Conditions de validité de la loi de Beer-Lambert ?", r: "**Un seul soluté absorbant**, à une longueur d'onde donnée, et concentrations **peu élevées** (< 0,1 mol·L⁻¹ en général)." },
  { q: "À quelle longueur d'onde fait-on les mesures d'un dosage spectrophotométrique ? Pourquoi ?", r: "À **λ<sub>max</sub>**, longueur d'onde du maximum d'absorption (lue sur le spectre) : la mesure y est la plus sensible et la plus précise." },
  /* Gaz parfait */
  { q: "Qu'est-ce qu'un gaz parfait ?", r: "Gaz dont les entités sont assez **éloignées pour ne pas interagir** et dont la somme des **volumes propres** est **négligeable** devant le volume total." },
  { q: "Équation d'état du gaz parfait, avec les unités ?", r: "$$P\\,V = n\\,R\\,T$$\n\nP en **Pa**, V en **m³**, n en mol, T en **K**, R = 8,31 J·mol⁻¹·K⁻¹." },
  { q: "Valeur de la constante des gaz parfaits R ?", r: "**R = 8,31 J·mol⁻¹·K⁻¹**" },
  { q: "Relation entre température en °C et en K ?", r: "**T (K) = θ (°C) + 273,15**\n\n0 °C = 273,15 K ; 25 °C = 298,15 K." },
  { q: "Unités de pression : 1 bar = ? Pa ; 1 hPa = ? Pa", r: "1 bar = **10⁵ Pa** ; 1 hPa = **10² Pa**. Pression atmosphérique ≈ 1 013 hPa ≈ 1,013 × 10⁵ Pa." },
  { q: "Conversions de volume pour PV = nRT ?", r: "1 L = **10⁻³ m³** ; 1 mL = 1 cm³ = **10⁻⁶ m³**." },
  { q: "V = 200 mL de dichlore à 25,0 °C sous 1,013 × 10⁵ Pa. Quantité de matière ?", r: "T = 298,15 K, V = 200 × 10⁻⁶ m³.\n\nn = PV/(RT) = 1,013 × 10⁵ × 200 × 10⁻⁶ / (8,31 × 298,2) = **8,18 × 10⁻³ mol**" },
  { q: "Domaine de validité du modèle du gaz parfait ?", r: "Pressions **inférieures à 5 × 10⁵ Pa** (5 bar) → tous les gaz dans les conditions usuelles. Montgolfière : oui ; bouteille de plongée (plusieurs bars) : non." },
  { q: "Définition du volume molaire Vₘ ? De quoi dépend-il ?", r: "Volume occupé par **une mole de gaz** à T et P données : Vₘ = V/n = **RT/P**. Il **ne dépend pas du gaz** (loi d'Avogadro-Ampère), seulement de T et P." },
  { q: "Loi d'Avogadro-Ampère ?", r: "À température et pression données, le **volume molaire est le même pour tous les gaz**." },
  { q: "Volume molaire à 25 °C et à 0 °C sous 1,01 × 10⁵ Pa ?", r: "25 °C (298,15 K) : Vₘ = 8,31 × 298,15 / 1,01 × 10⁵ = 2,45 × 10⁻² m³·mol⁻¹ = **24,5 L·mol⁻¹**\n\n0 °C (273,15 K) : **22,5 L·mol⁻¹**" },
  { q: "Comment passer d'un volume de gaz V à sa quantité de matière n ?", r: "**n = V / Vₘ** (ou n = PV/(RT))." },
]);
