/* Chapitre 1 — Réactions acide-base — CARTES MÉMO
   Une carte = { q: "question (recto)", r: "réponse (verso)" }. Markdown accepté. */
definirContenu("chimie/01-reactions-acide-base", "cartes", [
  { q: "Qu'est-ce qu'un **acide** au sens de Brönsted ?", r: "Une espèce chimique susceptible de **céder** un ion hydrogène H⁺.\n\nDemi-équation : Acide = autre espèce + H⁺" },
  { q: "Qu'est-ce qu'une **base** au sens de Brönsted ?", r: "Une espèce chimique susceptible de **capter** un ion hydrogène H⁺.\n\nDemi-équation : Base + H⁺ = autre espèce" },
  { q: "Qu'est-ce qu'un ion hydrogène H⁺ ?", r: "Un atome d'hydrogène qui a perdu son électron : un simple **proton**, avec une **lacune électronique**. Il n'existe jamais seul en solution." },
  { q: "Pourquoi dit-on qu'une demi-équation acido-basique est « formelle » ?", r: "Elle indique seulement un transfert de H⁺ ; cette étape n'existe pas réellement (H⁺ n'est jamais libre en solution). On l'écrit avec un signe **=**." },
  { q: "Demi-équation de l'ion oxonium H₃O⁺ en tant qu'acide ?", r: "H₃O⁺(aq) = H₂O(ℓ) + H⁺" },
  { q: "Demi-équation de l'ion hydroxyde HO⁻ en tant que base ?", r: "HO⁻(aq) + H⁺ = H₂O(ℓ)" },
  { q: "Demi-équation de l'acide éthanoïque CH₃–COOH ?", r: "CH₃–COOH(aq) = CH₃–COO⁻(aq) + H⁺\n\n(l'ion éthanoate est sa base conjuguée)" },
  { q: "Demi-équation de l'ammoniac NH₃ en tant que base ?", r: "NH₃(aq) + H⁺ = NH₄⁺(aq)\n\n(l'ion ammonium est son acide conjugué)" },
  { q: "Quels ions sont responsables des propriétés acides de l'acide chlorhydrique (H₃O⁺, Cl⁻), nitrique (H₃O⁺, NO₃⁻) et sulfurique (2 H₃O⁺, SO₄²⁻) ?", r: "**Seulement les ions oxonium H₃O⁺.** Cl⁻, NO₃⁻ et SO₄²⁻ sont des ions spectateurs." },
  { q: "Quel ion est responsable des propriétés basiques de la soude (Na⁺, HO⁻) et de la potasse (K⁺, HO⁻) ?", r: "**Seulement l'ion hydroxyde HO⁻.** Na⁺ et K⁺ sont des ions spectateurs." },
  { q: "Qu'est-ce qu'un ion spectateur ?", r: "Un ion présent dans la solution (pour assurer la neutralité électrique) mais qui ne participe pas à la réaction : il **n'apparaît pas** dans l'équation." },
  { q: "Sous quelle autre forme note-t-on parfois l'acide carbonique H₂CO₃ ? Pourquoi ?", r: "« CO₂, H₂O », car il se forme par dissolution du dioxyde de carbone dans l'eau. La notation H₂CO₃ est plus commode pour montrer son caractère acide." },
  { q: "Que fait apparaître la structure (schéma de Lewis) d'un **acide** de Brönsted ?", r: "Une **liaison polarisée** entre un H et un atome plus électronégatif (O, N…). Sa rupture libère H⁺.\n\nχO − χH > 0,4 et χN − χH > 0,4" },
  { q: "Que fait apparaître la structure (schéma de Lewis) d'une **base** de Brönsted ?", r: "Un atome (O, N…) portant un ou plusieurs **doublets non liants**, capables de combler la lacune électronique de H⁺." },
  { q: "Dans l'acide éthanoïque CH₃–COOH, quel hydrogène est cédé ?", r: "Celui du groupement carboxyle (liaison **O–H** polarisée). Les H du CH₃ sont liés au carbone, peu électronégatif : ils ne partent pas." },
  { q: "Qu'est-ce que la **base conjuguée** d'un acide AH ?", r: "L'espèce **A⁻** obtenue quand AH cède un H⁺. Elle peut à son tour capter un H⁺ : c'est une base." },
  { q: "Qu'est-ce que l'**acide conjugué** d'une base A⁻ ?", r: "L'espèce **AH** obtenue quand A⁻ capte un H⁺. Elle peut à son tour céder un H⁺ : c'est un acide." },
  { q: "Comment note-t-on un couple acide-base ? Que représente chaque côté ?", r: "**AH/A⁻** : la forme **acide à gauche**, la forme **basique à droite**. La base ne porte pas forcément une charge négative (ex. NH₄⁺/NH₃)." },
  { q: "Demi-équation générale d'un couple acide-base ?", r: "**AH = A⁻ + H⁺**" },
  { q: "Cite les couples de l'eau.", r: "H₃O⁺(aq) / H₂O(ℓ) (l'eau est la base)\n\nH₂O(ℓ) / HO⁻(aq) (l'eau est l'acide)" },
  { q: "Couples de l'acide carbonique et de l'ion hydrogénocarbonate ?", r: "H₂CO₃(aq) / HCO₃⁻(aq)\n\nHCO₃⁻(aq) / CO₃²⁻(aq)" },
  { q: "Couple de l'ion ammonium ?", r: "NH₄⁺(aq) / NH₃(aq)" },
  { q: "Qu'est-ce qu'un **indicateur coloré acido-basique** ?", r: "Une espèce formant un couple acide-base dont la forme acide et la forme basique ont des **couleurs différentes**. Ex. : hélianthine (rouge/jaune), BBT (jaune/bleu)." },
  { q: "Qu'est-ce qu'une **espèce amphotère** ?", r: "Une espèce qui peut se comporter **comme un acide ou comme une base** : elle appartient à deux couples acide-base. Ex. : H₂O, HCO₃⁻." },
  { q: "Pourquoi l'ion hydrogénocarbonate HCO₃⁻ est-il amphotère ?", r: "Il est **base** du couple H₂CO₃/HCO₃⁻ et **acide** du couple HCO₃⁻/CO₃²⁻." },
  { q: "Qu'est-ce que le zwitterion d'un acide α-aminé (ex. glycine) ?", r: "Sa forme portant à la fois **–NH₃⁺** (acide, conjugué de –NH₂) et **–COO⁻** (base, conjuguée de –COOH). Elle appartient à deux couples : elle est **amphotère**." },
  { q: "Comment est modélisée une **transformation acide-base** ?", r: "Par le **transfert d'un ion H⁺** de l'acide A₁H d'un couple (1) vers la base A₂⁻ d'un autre couple (2) :\n\nA₁H + A₂⁻ → A₁⁻ + A₂H" },
  { q: "Comment obtient-on l'équation d'une réaction acide-base à partir des demi-équations ?", r: "On écrit A₁H = A₁⁻ + H⁺ et A₂⁻ + H⁺ = A₂H, puis on fait la **somme membre à membre** : les H⁺ se simplifient.\n\nA₁H + A₂⁻ → A₁⁻ + A₂H" },
  { q: "Une réaction acide-base est-elle toujours totale ?", r: "**Non**, une telle réaction n'est pas toujours totale." },
  { q: "Équation de la réaction de détartrage (H₃O⁺ de l'acide chlorhydrique + carbonate CO₃²⁻ du tartre) ?", r: "H₃O⁺(aq) + CO₃²⁻(aq) → H₂O(ℓ) + HCO₃⁻(aq)\n\n(Cl⁻ et Ca²⁺ sont spectateurs)" },
  { q: "Équation de la réaction entre l'acide carbonique H₂CO₃ et les ions hydroxyde HO⁻ ?", r: "H₂CO₃(aq) + HO⁻(aq) → HCO₃⁻(aq) + H₂O(ℓ)\n\nCouples : H₂CO₃/HCO₃⁻ et H₂O/HO⁻" },
  { q: "Astuce : comment écrire directement l'équation quand on connaît les deux couples ?", r: "Écrire les couples **l'un sous l'autre** et relier « en croix » : l'acide d'un couple réagit avec la base de l'autre ; les produits sont la base du premier et l'acide du second." },
  { q: "Face à une base, comment se comporte une espèce amphotère ? Et face à un acide ?", r: "Face à une **base** → elle joue l'**acide** (cède H⁺).\n\nFace à un **acide** → elle joue la **base** (capte H⁺)." },
  { q: "Équation entre HCO₃⁻ et l'acide citrique C₆H₈O₇ ? Quel est le rôle de HCO₃⁻ ?", r: "HCO₃⁻(aq) + C₆H₈O₇(aq) → H₂CO₃(aq) + C₆H₇O₇⁻(aq)\n\nHCO₃⁻ joue le rôle de **base**." },
  { q: "Équation entre HCO₃⁻ et l'ammoniac NH₃ ? Quel est le rôle de HCO₃⁻ ?", r: "HCO₃⁻(aq) + NH₃(aq) → CO₃²⁻(aq) + NH₄⁺(aq)\n\nHCO₃⁻ joue le rôle d'**acide**." },
  { q: "Comment reconnaître une réaction acide-base dans une équation ?", r: "L'équation fait apparaître un **transfert d'ion H⁺** : une espèce a perdu exactement un H (acide → base conjuguée), une autre en a gagné un (base → acide conjugué)." },
  { q: "Équation de la réaction entre l'ammoniac NH₃ et l'ion oxonium H₃O⁺ ? Qui perd et qui gagne H⁺ ?", r: "NH₃(aq) + H₃O⁺(aq) → NH₄⁺(aq) + H₂O(ℓ)\n\nH₃O⁺ **perd** H⁺ (→ H₂O), NH₃ **gagne** H⁺ (→ NH₄⁺)." },
  { q: "Quel effet une réaction acide-base a-t-elle sur le pH ? Pourquoi ?", r: "Elle fait **varier le pH**, car le pH est lié à la concentration en ions H₃O⁺, qui change au cours de la réaction." },
  { q: "Que signifie le passage du BBT du jaune au bleu quand on ajoute de la soude à de l'acide éthanoïque ?", r: "Le pH **augmente** : le milieu est le siège d'une réaction acide-base (CH₃–COOH + HO⁻ → CH₃–COO⁻ + H₂O)." },
  { q: "Quelles précautions pour manipuler acides et bases ?", r: "Ce sont des substances **corrosives** (brûlures) : **blouse, gants, lunettes**. Ne pas mélanger acides et bases sans précaution ; ne pas verser d'eau dans une solution concentrée." },
  { q: "Qu'est-ce qu'un acide carboxylique ? un ion carboxylate ?", r: "Acide carboxylique : espèce portant le groupement **–COOH** en bout de chaîne (acide).\n\nIon carboxylate : espèce portant un groupement **–COO⁻** (sa base conjuguée)." },
  { q: "Qu'est-ce qu'une amine ? Acide ou base ?", r: "Composé dérivé de l'ammoniac NH₃ où au moins un H est remplacé par une chaîne carbonée (ex. méthylamine CH₃–NH₂). C'est une **base** (doublet non liant sur N)." },
]);
