/* Chapitre 1 — Réactions acide-base — VOCABULAIRE
   Un terme = { terme: "…", definition: "…" }. Le Markdown est accepté dans la définition. */
definirContenu("chimie/01-reactions-acide-base", "vocabulaire", [
  { terme: "Acide (de Brönsted)", definition: "Espèce chimique susceptible de **céder** un ion hydrogène H⁺. Demi-équation : Acide = autre espèce + H⁺." },
  { terme: "Base (de Brönsted)", definition: "Espèce chimique susceptible de **capter** un ion hydrogène H⁺. Demi-équation : Base + H⁺ = autre espèce." },
  { terme: "Ion hydrogène H⁺", definition: "Atome d'hydrogène ayant perdu son unique électron : il ne reste que le noyau (un proton). Il possède une lacune électronique et n'existe jamais seul en solution : il est toujours transféré d'un acide à une base." },
  { terme: "Demi-équation acido-basique", definition: "Écriture formelle du transfert d'un ion H⁺ pour un couple : AH = A⁻ + H⁺. Elle ne décrit pas une étape réelle, on l'écrit avec le signe =." },
  { terme: "Couple acide-base", definition: "Ensemble formé par un acide AH et sa base conjuguée A⁻, qui ne diffèrent que d'un ion H⁺. Il se note AH/A⁻ (acide à gauche, base à droite)." },
  { terme: "Base conjuguée", definition: "Espèce A⁻ obtenue quand l'acide AH cède un ion H⁺. Exemple : CH₃–COO⁻ est la base conjuguée de CH₃–COOH." },
  { terme: "Acide conjugué", definition: "Espèce AH obtenue quand la base A⁻ capte un ion H⁺. Exemple : NH₄⁺ est l'acide conjugué de NH₃." },
  { terme: "Espèce amphotère", definition: "Espèce qui peut se comporter comme un acide **ou** comme une base, car elle appartient à deux couples acide-base (une fois comme acide, une fois comme base). Exemples : H₂O, HCO₃⁻, le zwitterion des acides α-aminés." },
  { terme: "Ion spectateur", definition: "Ion présent dans la solution (pour assurer sa neutralité électrique) mais qui ne participe pas à la réaction : il n'apparaît pas dans l'équation. Exemples : Cl⁻ dans l'acide chlorhydrique, Na⁺ dans la soude." },
  { terme: "Liaison polarisée", definition: "Liaison entre deux atomes d'électronégativités très différentes (écart supérieur à 0,4) : les électrons de la liaison sont attirés vers l'atome le plus électronégatif, qui porte une charge partielle δ⁻, l'autre portant δ⁺. Les liaisons O–H et N–H sont polarisées." },
  { terme: "Électronégativité (χ)", definition: "Grandeur qui traduit la capacité d'un atome à attirer vers lui les électrons d'une liaison. O et N sont bien plus électronégatifs que H." },
  { terme: "Doublet non liant", definition: "Paire d'électrons de valence d'un atome qui ne participe à aucune liaison. Les atomes O et N en portent ; c'est grâce à lui qu'une base peut capter un H⁺." },
  { terme: "Lacune électronique", definition: "Case vide dans la structure électronique d'une espèce, qui peut accueillir un doublet d'électrons. L'ion H⁺ en possède une." },
  { terme: "Transformation (réaction) acide-base", definition: "Transformation modélisée par le transfert d'un ion H⁺ de l'acide d'un couple vers la base d'un autre couple : A₁H + A₂⁻ → A₁⁻ + A₂H. Elle n'est pas toujours totale." },
  { terme: "Réaction totale", definition: "Réaction qui se poursuit jusqu'à la disparition complète d'au moins un réactif (le réactif limitant). Une réaction acide-base n'est pas toujours totale." },
  { terme: "Indicateur coloré acido-basique", definition: "Espèce chimique formant un couple acide-base dont la forme acide et la forme basique ont des couleurs différentes. Exemples : hélianthine (rouge / jaune), bleu de bromothymol ou BBT (jaune / bleu)." },
  { terme: "BBT (bleu de bromothymol)", definition: "Indicateur coloré : jaune en milieu acide, bleu en milieu basique (vert autour de sa zone de virage, pH 6,0 à 7,6)." },
  { terme: "Hélianthine", definition: "Indicateur coloré dont la forme acide est rouge et la forme basique jaune (zone de virage : pH 3,1 à 4,4)." },
  { terme: "Ion oxonium H₃O⁺", definition: "Acide du couple H₃O⁺/H₂O. Les propriétés acides de l'acide chlorhydrique, nitrique ou sulfurique en solution sont dues seulement à sa présence." },
  { terme: "Ion hydroxyde HO⁻", definition: "Base du couple H₂O/HO⁻. Les propriétés basiques de la soude et de la potasse sont dues seulement à sa présence." },
  { terme: "Acide chlorhydrique", definition: "Solution aqueuse (H₃O⁺(aq), Cl⁻(aq)) obtenue en dissolvant du chlorure d'hydrogène HCl dans l'eau. L'ion Cl⁻ est spectateur." },
  { terme: "Acide nitrique", definition: "Solution aqueuse (H₃O⁺(aq), NO₃⁻(aq)). L'ion nitrate NO₃⁻ est spectateur." },
  { terme: "Acide sulfurique", definition: "Solution aqueuse (2 H₃O⁺(aq), SO₄²⁻(aq)). L'ion sulfate SO₄²⁻ est spectateur." },
  { terme: "Soude (hydroxyde de sodium)", definition: "Solution aqueuse (Na⁺(aq), HO⁻(aq)). Base très utilisée, présente dans les déboucheurs de canalisations." },
  { terme: "Potasse (hydroxyde de potassium)", definition: "Solution aqueuse (K⁺(aq), HO⁻(aq))." },
  { terme: "Acide carbonique H₂CO₃", definition: "Acide formé lors de la dissolution du dioxyde de carbone CO₂ dans l'eau (on le note parfois CO₂, H₂O). Acide du couple H₂CO₃/HCO₃⁻." },
  { terme: "Ion hydrogénocarbonate HCO₃⁻", definition: "Espèce amphotère : base du couple H₂CO₃/HCO₃⁻ et acide du couple HCO₃⁻/CO₃²⁻." },
  { terme: "Ion carbonate CO₃²⁻", definition: "Base du couple HCO₃⁻/CO₃²⁻. Présent dans le tartre CaCO₃(s)." },
  { terme: "Ammoniac NH₃ / ion ammonium NH₄⁺", definition: "Couple NH₄⁺/NH₃ : l'ammoniac est une base, l'ion ammonium son acide conjugué." },
  { terme: "Acide carboxylique", definition: "Espèce chimique comportant le groupement carboxyle –COOH en bout de chaîne. C'est un acide (la liaison O–H du carboxyle est polarisée). Exemple : acide éthanoïque CH₃–COOH." },
  { terme: "Ion carboxylate", definition: "Espèce chimique comportant un groupement –COO⁻. C'est la base conjuguée d'un acide carboxylique. Exemple : ion éthanoate CH₃–COO⁻." },
  { terme: "Amine", definition: "Composé organique dérivé de l'ammoniac NH₃ dont au moins un atome d'hydrogène a été remplacé par une chaîne carbonée. C'est une base (l'azote porte un doublet non liant). Exemple : méthylamine CH₃–NH₂." },
  { terme: "Acide α-aminé", definition: "Molécule portant à la fois un groupement carboxyle –COOH et un groupement amino –NH₂ sur le même carbone. Exemple : la glycine. Sa forme zwitterion est amphotère." },
  { terme: "Zwitterion", definition: "Forme d'un acide α-aminé portant à la fois –NH₃⁺ (forme acide) et –COO⁻ (forme basique) : globalement neutre mais avec deux charges opposées. Il est amphotère." },
  { terme: "Tartre / détartrage", definition: "Le tartre est du carbonate de calcium CaCO₃(s). Le détartrer, c'est faire réagir ses ions carbonate CO₃²⁻ (base) avec un acide (par exemple H₃O⁺) : H₃O⁺ + CO₃²⁻ → H₂O + HCO₃⁻." },
  { terme: "pH", definition: "Grandeur liée à la concentration en ions oxonium H₃O⁺ d'une solution (étudiée au chapitre 2). Une réaction acide-base fait varier le pH." },
]);
